// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8lEN4LvbBPtM36DEP3ekcPBopqjkZFI',
    appId: '1:696089925193:web:71837eaa2434e32a5d1198',
    messagingSenderId: '696089925193',
    projectId: 'whatsappclone-c5a0a',
    authDomain: 'whatsappclone-c5a0a.firebaseapp.com',
    storageBucket: 'whatsappclone-c5a0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo3NeCyTlbVvrdH5NhhB8Gapju1ss0Ims',
    appId: '1:696089925193:android:345ad66957c3bccb5d1198',
    messagingSenderId: '696089925193',
    projectId: 'whatsappclone-c5a0a',
    storageBucket: 'whatsappclone-c5a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjRMvCV-_0ocjSFKeQyMs-7EkI-DyTd0',
    appId: '1:696089925193:ios:c8d294f099bd35315d1198',
    messagingSenderId: '696089925193',
    projectId: 'whatsappclone-c5a0a',
    storageBucket: 'whatsappclone-c5a0a.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
